/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: mohsen
 *
 * Created on February 11, 2023, 5:44 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE                   1
#define INTERRUPT_FEATURE_DISABLE                  0

#define INTERRUPT_PRIORTY_LEVELS_ENABLE            INTERRUPT_FEATURE_DISABLE

#define INTERRUPT_INTx_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE
#define INTERRUPT_ONCHANGE_FEATURE_ENABLE          INTERRUPT_FEATURE_ENABLE

#define ADC_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_ENABLE

#define TMR0_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE
#define TMR1_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE
#define TMR2_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE
#define TMR3_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE

#define CCP1_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE
#define CCP2_INTERRUPT_FEATURE_ENABLE              INTERRUPT_FEATURE_ENABLE

#define USART_TX_INTERRUPT_FEATURE_ENABLE          INTERRUPT_FEATURE_ENABLE
#define USART_RX_INTERRUPT_FEATURE_ENABLE          INTERRUPT_FEATURE_ENABLE

#define SPI_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_ENABLE

#define I2C_INTERRUPT_FEATURE_ENABLE               INTERRUPT_FEATURE_DISABLE

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

